### ISSUE TITLE
Plan for SciPy announcement

### ISSUE THREAD

**Issue by yuvipanda** [voila-gallery/gallery#27]
I'm guessing @sylvaincorlay and others will announce Voila at SciPy. We should make sure the Gallery is upto the task of the folks who will be coming to check it out.

1. Make sure our instance is big enough
2. Have some monitoring & metrics in place (so we know how many people showed up)
3. Have more examples?
4. Quick design refresh
5. Make sure idle culling is in place.

Other things to do? /cc @pbugnion @jtpio

**Comment by jtpio** [comment]
Those are all good points. Also:

- [x] HTTPS by default for [voila-gallery.org](https://voila-gallery.org)
- [ ] A tutorial so people can deploy their own gallery? (including links to the existing guides in TLJH)

**Comment by martinRenou** [comment]
- [ ] Support for ~~themes~~ templates in the gallery (if that's not already done, or I suppose it's related to this https://github.com/QuantStack/voila/pull/201)

**Comment by jtpio** [comment]
@martinRenou both themes and templates?

**Comment by martinRenou** [comment]
Sorry, I meant templates :)

**Comment by maartenbreddels** [comment]
FYI, this is the material for the tutorial on widgets:
https://github.com/jupyter-widgets/tutorial/pull/33

It will include instructions for mybinder, but we hope to do more :)

I feel torn about the templates, I think before we let people make new templates, we should have a stable template system. If we push out an early release, we might have to break it twice (once for the directory layout+nbconvert coop., once for the progressive rendering). So just be aware that this area is still moving.

**Comment by SylvainCorlay** [comment]
Thanks @yuvipanda for opening this.

FYI, @maartenbreddels and @martinRenou will be giving the talk about voila. I will finally not attend scipy (going to give another talk at CICM about voila as well). There should also be some voila chapter in the jupyter widgets tutorial.

**Comment by jtpio** [comment]
I think the current state of the gallery together with the open PRs (https://github.com/voila-gallery/gallery/pull/48, https://github.com/voila-gallery/gallery/pull/45 and https://github.com/voila-gallery/gallery/pull/50) cover most of the points listed above.

The current instance is a [b2-30](https://www.ovh.com/world/public-cloud/prices/) that comes with 30 GB RAM, 8 vCores and 200 GB SSD. That should be enough to start with.

Regarding the templates this is something that we need to handle in voila before exposing it in the gallery.

For the idle culling, there is a basic activity timeout which means that the notebook servers will be shut down if they become inactive (same values as for mybinder.org). There is no user culling yet, the temporary users are still kept in the JupyterHub database. This is something that can tackled later on.

For the monitoring and metrics, maybe @yuvipanda has something we can setup quickly? (would using the `/metrics` endpoint be enough?)

**Comment by jtpio** [comment]
Closing as the remaining points mentioned here now have their own issues.
