### ISSUE TITLE
The render-stl example gives an error 500 right now

### ISSUE THREAD

**Issue by deeplook** [voila-gallery/gallery#54]
No more text, sorry.

**Comment by jtpio** [comment]
Indeed, thanks @deeplook for the report.

It looks like we are facing the same issue as in https://github.com/QuantStack/voila/issues/224 when building the example with `repo2docker`, related to the Pygments version (2.3 instead of 2.4)

**Comment by jtpio** [comment]
https://github.com/voila-gallery/render-stl/pull/6 should fix it.

This example was using a `requirements.txt`, and it looks like pip is not able to install Pygment 2.4.2 when Pygments 2.3.1 is already there from other dependencies (ipython, nbconvert...).

Voila requires Pygments as an indirect dependency: `voila 0.1.6 -> jupyterlab-pygments 0.1.0 -> pygments >= 2.4.1`

**Comment by jtpio** [comment]
Fixed by switching to conda's `environment.yml`.

Also, `pygments>=2.4.1` is now a direct dependency of voila so the next release should fix the remaining installation issues.
