### ISSUE TITLE
Point voila-gallery.org to a floating IP

### ISSUE THREAD

**Issue by yuvipanda** [voila-gallery/gallery#55]
IIRC, currently voila-gallery.org is pointed at the public IP of a single instance.

Instead, we should use a [floating IP](https://labs.ovh.com/public-cloud-l3-services) that can then be associated with any instance as needed. This will let us do failovers when necessary, and give us a lot of flexibility. 

It *should* be easy to migrate as well:

1. Create a floating IP
2. Point it to current instance, while keeping current instance's public IP
3. Point domain to floating IP

This would make sure we don't have a failure during DNS switchover period.

**Comment by jtpio** [comment]
That's a good point, especially if we keep running a single instance of the gallery but would like to tear it down and up at will.

**Comment by jtpio** [comment]
Trying to follow [this guide](https://labs.ovh.com/public-cloud-l3-services) to setup the floating IP from the command line:

```
openstack router create myrouter
```

Gives the following error:

```
ConflictException: 409: Client Error for url: https://network.compute.gra5.cloud.ovh.net/v2.0/routers, Quota exceeded for resources: ['router'].
```

I have opened a support ticket on OVH.

**Comment by jtpio** [comment]
Received a reply for the support ticket today:


> The floating ip service being in beta, we have no information to support.
>
> If you have any problems or specific needs regarding this service, I invite you to contact the people managing this beta.
