### ISSUE TITLE
Move to the voila-dashboards GitHub organization?

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-gallery/gallery#71]
We are moving voilà to the voila-dashboards organization, as well as the voilà templates that we work on...

Should voila-gallery also be moved to this organization? It may make sense to only have the examples of the public voila-gallery.org deployment in this organization? Thoughts?

cc @yuvipanda @jtpio

**Comment by jtpio** [comment]
Fine for moving over to `voila-dashboards`.

If this organization now only contains examples, it could also be renamed to `voila-gallery-examples` or `voila-examples`.

**Comment by SylvainCorlay** [comment]
The move is done and everyone has been invited to the organization!
