### ISSUE TITLE
Improve example cards

### ISSUE THREAD

**Issue by jtpio** [voila-gallery/gallery#72]
As a follow-up for https://github.com/voila-gallery/gallery/pull/70, and suggested by @SylvainCorlay in https://github.com/voila-gallery/gallery/pull/70#issuecomment-535518678, we can do a second pass on the new visual identity:

> - remove the Launch button to make the whole div a launch button (maybe with a transparent > play button on hover)
> - probably remove the Source button to be replaced with a github link in the corner...

**Comment by SylvainCorlay** [comment]
> github

Quick thought on this: maybe another logo than github in case we decide to support gitlab or arbitrary git URLs.

**Comment by jtpio** [comment]
That should already be supported, since the examples are built with `repo2docker` (which handles arbitrary git URLs).

**Comment by jtpio** [comment]
Fixed by https://github.com/voila-gallery/gallery/pull/73
